name: Build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake cmake-data git build-essential autoconf automake libtool texinfo bison flex pkg-config python3 python-is-python3
        echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        locale-gen
    - name: Build
      run: |
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        mkdir build
        cd build
        export LANG=en_US.UTF-8
        cmake ..
        LANG=en_US.UTF-8 make -j1 tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-linux
        path: build/*.tar.bz2
  build-macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Build
      run: |
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        brew install autoconf automake libtool
        mkdir build
        cd build
        cmake ..
        make -j1 tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-macos
        path: build/*.tar.bz2
